# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1620546375);
user_pref("app.update.lastUpdateTime.background-update-timer", 1620546615);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1620546495);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1620546255);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1620546735);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/Users/Adrian/Downloads");
user_pref("browser.history.last_page_visited", "http://pyongyangracer.co/");
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1620553755372");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1620555528372");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1620546222149");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1620567822149");
user_pref("browser.search.countryCode", "AU");
user_pref("browser.search.region", "AU");
user_pref("browser.startup.homepage", "http://pyongyangracer.co");
user_pref("browser.startup.homepage_override.mstone", "rv:60.0");
user_pref("browser.tabs.forceHide", true);
user_pref("calendar.categories.names", "Anniversary,Birthday,Business,Calls,Clients,Competition,Customer,Favorites,Follow up,Gifts,Holidays,Ideas,Issues,Meeting,Miscellaneous,Personal,Projects,Public Holiday,Status,Suppliers,Travel,Vacation");
user_pref("calendar.category.color.anniversary", "#333333");
user_pref("calendar.category.color.birthday", "#996633");
user_pref("calendar.category.color.business", "#FFFFCC");
user_pref("calendar.category.color.calls", "#99FF99");
user_pref("calendar.category.color.clients", "#FF9900");
user_pref("calendar.category.color.competition", "#CC9933");
user_pref("calendar.category.color.customer", "#CCCCCC");
user_pref("calendar.category.color.favorites", "#3366FF");
user_pref("calendar.category.color.follow_up", "#6600CC");
user_pref("calendar.category.color.gifts", "#FF99FF");
user_pref("calendar.category.color.holidays", "#663366");
user_pref("calendar.category.color.ideas", "#003333");
user_pref("calendar.category.color.issues", "#99FFFF");
user_pref("calendar.category.color.meeting", "#FFFF66");
user_pref("calendar.category.color.miscellaneous", "#FFCC00");
user_pref("calendar.category.color.personal", "#003333");
user_pref("calendar.category.color.projects", "#FFCC99");
user_pref("calendar.category.color.public_holiday", "#FFCC66");
user_pref("calendar.category.color.status", "#FFFF33");
user_pref("calendar.category.color.suppliers", "#000099");
user_pref("calendar.category.color.travel", "#663300");
user_pref("calendar.category.color.vacation", "#660000");
user_pref("calendar.timezone.local", "Australia/Sydney");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_SCREEN_RESOLUTION_ENUMERATED_PER_USER\":\"2.53.4\"}");
user_pref("devtools.toolbox.selectedTool", "netmonitor");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.e10sMultiBlockedByAddons", true);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installedDistroAddon.inspector@mozilla.org", true);
user_pref("extensions.installedDistroAddon.{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}", true);
user_pref("extensions.installedDistroAddon.{e2fda1a4-762b-4020-b5ad-a41df1933103}", true);
user_pref("extensions.lastAppBuildId", "20200907075030");
user_pref("extensions.lastAppVersion", "2.53.4");
user_pref("extensions.lastPlatformVersion", "60.5.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("gecko.handlerService.migrated", true);
user_pref("general.open_location.last_url", "css italics");
user_pref("general.skins.selectedSkin", "modern/1.0");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.default_charsets.migrated", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("services.blocklist.addons.checked", 1620545727);
user_pref("services.blocklist.clock_skew_seconds", 769);
user_pref("services.blocklist.gfx.checked", 1620545727);
user_pref("services.blocklist.last_update_seconds", 1620545727);
user_pref("services.blocklist.pinning.checked", 1620545727);
user_pref("services.blocklist.plugins.checked", 1620545727);
user_pref("shell.checkDefaultApps", 0);
user_pref("shell.checkDefaultClient", false);
user_pref("signon.importedFromSqlite", true);
user_pref("suite.migration.version", 5);
